### ISSUE TITLE
Running bug?

### ISSUE THREAD

**Issue by the-centry** [SymbiFlow/symbiflow-xc-fasm2bels#59]
For  analysis of a7_100t's fasm,I use the command as this:
`**/root/Desktop/symbiflow/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/python3 -mfasm2bels --db_root /root/Desktop/symbiflow/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/share/symbiflow/prjxray-db/artix7 --connection_database /root/Desktop/fasm2bels/devices/xc7a100t-virt/channels.db --fasm_file /root/Desktop/fasm2bels/artix7_100t-xc7a100t-virt-xc7a100t-test/top.fasm --verilog_file /root/Desktop/fasm2bels/test.v --part xc7a100tcsg324-1 --vpr_grid_map /root/Desktop/fasm2bels/devices/xc7a100t-virt/vpr_grid_map.csv --eblif /root/Desktop/fasm2bels/artix7_100t-xc7a100t-virt-xc7a100t-test/top.eblif**`
**But it always prompt error such as:** 
`Traceback (most recent call last):
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/third_party/symbiflow-xc-fasm2bels/fasm2bels/__main__.py", line 4, in <module>
    main()
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/third_party/symbiflow-xc-fasm2bels/fasm2bels/fasm2bels.py", line 443, in main
    process_tile(top, tile, tile_features)
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/third_party/symbiflow-xc-fasm2bels/fasm2bels/fasm2bels.py", line 107, in process_tile
    PROCESS_TILE[tile_type](top.conn, top, tile, tile_features)
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/third_party/symbiflow-xc-fasm2bels/fasm2bels/models/clb_models.py", line 2066, in process_clb
    process_slice(top, slices[s])
  File "/root/Desktop/symbiflow/symbiflow-arch-defs/third_party/symbiflow-xc-fasm2bels/fasm2bels/models/clb_models.py", line 1827, in process_slice
    assert False
AssertionError`

**Comment by mithro** [comment]
Please upload your `/root/Desktop/fasm2bels/artix7_100t-xc7a100t-virt-xc7a100t-test/top.fasm` and `/root/Desktop/fasm2bels/artix7_100t-xc7a100t-virt-xc7a100t-test/top.eblif` file somewhere and link it from this bug report.

**Comment by the-centry** [comment]
[https://github.com/the-centry/symbiflow-xc-fasm2bels/tree/master/tests/test_data/uart_test](https://github.com/the-centry/symbiflow-xc-fasm2bels/tree/master/tests/test_data/uart_test)

**Comment by the-centry** [comment]
> Please upload your `/root/Desktop/fasm2bels/artix7_100t-xc7a100t-virt-xc7a100t-test/top.fasm` and `/root/Desktop/fasm2bels/artix7_100t-xc7a100t-virt-xc7a100t-test/top.eblif` file somewhere and link it from this bug report.

I found the reason of wrong,I use the top.fasm gennerated by symbiflow and after I use the fasm generated by top.bit and the error disappeared!
Thanks so much!

**Comment by zliu1Charlotte** [comment]
Hi where did you get this  --connection_database /root/Desktop/fasm2bels/devices/xc7a100t-virt/channels.db 
Thanks!
